# this is a test yaml
experiment_name: pct-ape64
dataset:
  type: modelnet40
  path: modelnet40_normal_resampled
  num_points: 1024
  bins: 64
model:
  type: PCT # PCT or PointTransformer
  pretrained: # leave blank if none; directory otherwise
  components:
    num_layers: 4
    dropout_p: 0.5
    input_embedding: 
      included: True
      d_model: 256
      pos_enc: ape
      neighbor: True
    attention:
      shared_weights: True
      offset: True
      d_qk: 64
      d_v: 256
      scale: l1
      num_heads: 1
    concat: True # always check
    pool: max
optimizer:
  type: Adam # SGD or Adam
  lr: 1e-04
  betas: [0.9, 0.999]
  eps: 1e-08
  weight_decay: 1e-04
scheduler:
  type: StepLR
  step_size: 50
  gamma: 0.3
train:
  epochs: 200
  batch_size: 16
  workers: 4
save_data:
  save_log: True
  save_model: True
