# this is a test yaml
experiment_name: npct-sinusoidal-4qk4v-4emb.txt
dataset:
  type: modelnet40
  path: modelnet40
  num_points: 1024
model:
  type: PCT # PCT or PointTransformer
  pretrained: # leave blank if none; directory otherwise
  components:
    num_layers: 4
    dropout_p: 0.5
    input_embedding: 
      included: True
      d_model: 4
      pos_enc: sinusoidal
      k: 16
    attention:
      shared_weights: False
      offset: False
      d_qk: 4
      d_v: 4
      scale: root
      num_heads: 1
    concat: True # always check
    pool: max
optimizer:
  type: SGD # SGD or Adam
  lr: 0.01
  momentum: 0.9
  weight_decay: 5e-4
scheduler:
  type: CosineAnnealingLR
  eta_min: 0.01
train:
  epochs: 250
  batch_size: 32
  workers: 8
save_data:
  save_log: True
  save_model: True
