# this is a test yaml
experiment_name: npct-sgrpe
dataset:
  type: modelnet40
  path: modelnet40
  num_points: 1024
  bins: 16
model:
  type: PCT # PCT or PointTransformer
  pretrained: # leave blank if none; directory otherwise
  components:
    num_layers: 4
    dropout_p: 0.5
    input_embedding: 
      included: True
      d_model: 128
      pos_enc: sgrpe
      sigma: 1
    attention:
      shared_weights: False
      offset: False
      d_qk: 32
      d_v: 128
      scale: root
      num_heads: 1
    concat: True # always check
    pool: max
optimizer:
  type: SGD # SGD or Adam
  lr: 0.01
  eps: 1e-08
  weight_decay: 1e-4
scheduler:
  type: CosineAnnealingLR
  eta_min: 0.01
train:
  epochs: 100
  batch_size: 32
  workers: 8
save_data:
  save_log: True
  save_model: True
